apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: my-container # to edit
              image: # to fill
              envFrom:
                - configMapRef:
                    name: main-configmap
              env:
                - name: username
                  valueFrom:
                    secretKeyRef:
                      name: db-secret
                      key: username
                - name: password
                  valueFrom:
                    secretKeyRef:
                      name: db-secret
                      key: password
              command: ["python3"]
              args: ["bepa.py"]
          restartPolicy: OnFailure
