apiVersion: v1
kind: Service

metadata:
  name: peyk-service
  labels:
    kubernetes.app: data-source
    app: peyk-app

spec:
  type: ClusterIP
  selector:
    app: peyk-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000